#!/usr/bin/env python3
"""Merge the per-language translation parts into the ES modules the app loads.

The English column is declared inline at each t() call site and dumped to
app/i18n/source/en.json by `node tools/smoke.mjs --dump`. Translators (human or
otherwise) work on that file, split into parts; this script stitches the parts
back together, checks that every placeholder survived, and writes app/i18n/<lang>.js.

Run:  python3 tools/build-i18n.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'app' / 'i18n' / 'source'
LANGS = ['ar', 'hi', 'bn', 'ps']

PLACEHOLDER = re.compile(r'{(\w+)}')


def load_parts(prefix):
    merged = {}
    for path in sorted(SRC.glob(f'{prefix}-part*.json')):
        merged.update(json.loads(path.read_text()))
    return merged


def main():
    english = json.loads((SRC / 'en.json').read_text()) if (SRC / 'en.json').exists() else load_parts('en')
    if not english:
        sys.exit('No English source. Run: node tools/smoke.mjs --dump app/i18n/source/en.json')

    problems = 0
    for lang in LANGS:
        table = load_parts(lang)
        clean = {}
        dropped = []
        for key, value in table.items():
            if key not in english:
                continue                                    # stale key, ignore
            if not isinstance(value, str) or not value.strip():
                continue
            # A translation that lost a placeholder would render "{n}" or an
            # empty slot to a user, so it is dropped and falls back to English
            # (WF-763) rather than shipping broken.
            if PLACEHOLDER.findall(english[key]) and \
               set(PLACEHOLDER.findall(value)) != set(PLACEHOLDER.findall(english[key])):
                dropped.append(key)
                continue
            clean[key] = value

        out = ROOT / 'app' / 'i18n' / f'{lang}.js'
        body = json.dumps(clean, ensure_ascii=False, indent=1, sort_keys=True)
        out.write_text(
            f'/* {lang} — GENERATED by tools/build-i18n.py from app/i18n/source/{lang}-part*.json.\n'
            f'   Do not edit here; edit the source and re-run the script.\n'
            f'   Keys not present fall back to English and are logged (WF-763). */\n'
            f'export default {body};\n'
        )
        pct = round(100 * len(clean) / len(english)) if english else 0
        note = f'  ({len(dropped)} dropped for placeholder mismatch)' if dropped else ''
        print(f'{lang}: {len(clean)}/{len(english)} keys — {pct}%{note}')
        if dropped:
            print(f'     e.g. {dropped[:5]}')
            problems += len(dropped)

    print(f'english source: {len(english)} keys')
    return 0


if __name__ == '__main__':
    sys.exit(main())
